apiVersion: apps/v1
kind: Deployment
metadata:
  name: osa1-whereami
  namespace: test2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: osa1-whereami
  template:
    metadata:
      labels:
        app: osa1-whereami
    spec:
      containers:
        - image: asia-northeast1-docker.pkg.dev/kzs-sandbox/public/whereami:1.0.2
          name: osa1-whereami
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: VERSION
              value: "v1"
            - name: KIND
              value: "osa1-test-app"
---
apiVersion: v1
kind: Service
metadata:
  name: osa1-whereami
  namespace: test2
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: osa1-whereami
  type: ClusterIP
---
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
  namespace: test2
  name: osa1-whereami
